Add dependentMaxes rate limiting config
platformatic/ai-warp-old pull request #10
Opened 2024-03-26 20:30 UTC by flakey5

Provides a simple way to associate JWT claims with different rate limits

2024-04-01 08:25 UTC, mcollina requested changes
tests are needed

---

Can you also send an example to fastify-rate-limiting with this approach? A doc/example would be good.

2024-04-01 08:25 UTC, mcollina commented on lib/schema.ts
> +        dependentMaxes: {
Please bikeshed a different name, this is very unclear.

2024-04-01 08:25 UTC, mcollina commented on index.ts
> +          for (const dependentMax of dependentMaxes) {
avoid this loop and build a lookup table

2024-04-01 08:25 UTC, mcollina commented on index.ts
> +          !(req.user instanceof Buffer)
I don't think user could ever be a Buffer

2024-04-02 22:25 UTC, flakey5 commented on lib/schema.ts
> +        dependentMaxes: {
How about `maxByClaims` or `maxFromClaims`?

2024-04-02 22:45 UTC, flakey5 commented on index.ts
> +          for (const dependentMax of dependentMaxes) {
Would it be better to loop through the claims in `req.user` and see if any are in the lookup table? Or would it be better to just have one claim that the max depends on and we can look for it in the lookup table.

E.g.
```typescript
// Loop through req.user claims
// Same/similar config
for (const claim of Object.keys(req.user)) {
  // check if exists in lookup table and equals specific value
}

// Or just one claim
// config:
{
  max: {
    claim: 'aiWarpPremium',
    values: {
      'true': 200,
      'false': 100
    }
  }
} 
// index.ts
const { claim, values } = config.rateLimiting.max
if (claim in req.user) {
  return values[req.user[claim]];
} 
```

2024-04-09 10:02 UTC, mcollina commented on index.ts
> +          for (const dependentMax of dependentMaxes) {
sgtm to that

2024-04-09 10:02 UTC, mcollina commented on lib/schema.ts
> +        dependentMaxes: {
`maxByClaims` is good

2024-04-10 05:23 UTC, mcollina commented
CI is failing

2024-04-11 08:08 UTC, mcollina approved these changes
lgtm

2024-04-11 15:33 UTC, merged