Basic functionality
platformatic/ai-warp-old pull request #2
Opened 2024-03-05 16:35 UTC by flakey5

Can send requests to OpenAI and Mistral and return the response

2024-03-05 17:25 UTC, mcollina commented on lib/generator.ts
> +      greeting: 'Hello world!',
remove

2024-03-05 17:25 UTC, mcollina commented on lib/generator.ts
> +      },
rmeove

2024-03-05 17:25 UTC, mcollina commented on lib/generator.ts
> +      },
remove

2024-03-05 17:25 UTC, mcollina commented on lib/generator.ts
> +      PLT_GREETING_TEXT: this.config.greeting ?? 'Hello world!',
remove

2024-03-05 17:25 UTC, mcollina commented on lib/schema.ts
> +    },
remove

2024-03-05 17:25 UTC, mcollina commented on plugins/api.ts
> +      const parseResult = PromptRequestSchema.safeParse(request.body);
Why are you validating the body twice? Just leverage the built-in validation. You can also use Zod for that.

2024-03-05 17:25 UTC, mcollina commented on plugins/api.ts
> +      }
should be `app.ai.warp(...)`, where this model is created inside a plugin. Essentially you have a model that set up an interface, and this code stay the same independently.

2024-03-05 17:25 UTC, mcollina commented on plugins/example.ts
> +}
remove this file

2024-03-06 10:07 UTC, mcollina requested changes

2024-03-06 10:07 UTC, mcollina commented on ai-providers/mistral.ts
> +     */
this file seems to be 4 char spaces (or tabs?). Implement a linter.

2024-03-06 10:07 UTC, mcollina commented on plugins/warp.ts
> +    if (model.startsWith('openai')) {
Implement a factory pattern for the AIModels, so that this if is not needed at all:

```js
const ask = build({ provider: 'openai', apiKey })
...
await ask(decoratedPrompt)
```

2024-03-07 09:39 UTC, mcollina commented on lib/schema.ts
> +      // ],
Why the if-else? There is no need for this:

1. use oneOf
2. remove the if-then-else
3. structure it with keys instead.

Valid config for this should be:

```json
{
  "aiProvider": {
    "openai": {
      "model": "..",
      "apiKey": ".."
    }
  }
}
```

Keep it simple. JSON Schema allows you to get _very fancy_, but 99% of the time the result is too complex.

2024-03-07 09:40 UTC, mcollina commented on plugins/api.ts
> +    handler: async (request: FastifyRequest<{ Body: PromptRequest }>): Promise<PromptResponse> => {
Use the type provider instead https://www.npmjs.com/package/fastify-type-provider-zod or https://github.com/fastify/fastify-type-provider-typebox.

I personally prefer the latter because it's easier to get good OpenAPI integration.

2024-03-07 09:41 UTC, mcollina commented on plugins/warp.ts
> +        status: 'success',
can status be anything but success?

2024-03-07 09:41 UTC, mcollina commented on plugins/warp.ts
> +      const provider = build(providerName, apiKey)
move this outside of the warp function

2024-03-07 09:42 UTC, mcollina commented on ai-providers/mistral.ts
> +      throw new Error('Mistral returned no responses')
please use the fastify-error module

2024-03-08 04:38 UTC, flakey5 commented
One thing to note: `mistral.ts` is still throwing errors since the client is in esm and the build is in cjs. Tried changing the build to esm but node still isn't a fan of that despite the fact that it should be working, and dynamically importing just gets transpiled to a `require()`. Will take a further look tmow

2024-03-13 18:10 UTC, mcollina commented on tsconfig.json
> +    "module": "commonjs",
You might want to set this to nodenext and configure everything to be esm. I _think_ it might solve your ESM issues.

2024-03-13 18:10 UTC, mcollina commented on plugins/warp.ts
> +  const provider = build(config)
It's likely better to not pass the full config but only the limited segment we need.

2024-03-15 23:57 UTC, flakey5 commented
Is this good to merge? Going off of #1, most of it is here. An exception is streaming which I should be able to figure out next week, but I'd prefer if that was in a separate pr so this one doesn't keep growing.

2024-03-19 23:27 UTC, merged