Streaming
platformatic/ai-warp-old pull request #4
Opened 2024-03-19 23:46 UTC by flakey5

2024-03-20 07:57 UTC, mcollina requested changes

2024-03-20 07:57 UTC, mcollina commented on plugins/api.ts
> +          true,
prefer an object over poisional arguments.
However I think it's better to have a separate method for streaming.

2024-03-20 07:57 UTC, mcollina commented on plugins/api.ts
> +          }
Prefer rejecting the promise over having a callback.
However, because you are returning a stream, this is not exactly possible. Specifically, `reply.send()` would not work.

2024-03-20 07:57 UTC, mcollina commented on plugins/api.ts
> +          return new InternalServerError()
```suggestion
         const err = new InternalServerError()
         err.cause = exception
         throw err
```

2024-03-20 07:57 UTC, mcollina commented on plugins/api.ts
> +        }
this should not be possible

2024-03-20 07:57 UTC, mcollina commented on plugins/api.ts
> +        return response
I'm pretty sure response is not following the event-stream format. Please check.

2024-03-20 07:57 UTC, mcollina commented on ai-providers/mistral.ts
> +class MistralByteSource implements UnderlyingByteSource {
Can we something simpler than this? Why is this required?

2024-03-20 07:57 UTC, mcollina commented on ai-providers/open-ai.ts
> +class OpenAiByteSource implements UnderlyingByteSource {
Can we something simpler than this? Why is this required?

2024-03-20 21:12 UTC, flakey5 commented on ai-providers/open-ai.ts
> +class OpenAiByteSource implements UnderlyingByteSource {
The `toReadableStream` function returns a polyfilled `ReadableStream`. In almost every functional sense it's almost exactly the same as Node's impl, but they're still two different types in the eyes of Node's internal type checking (or more specifically here iirc https://github.com/nodejs/node/blob/c714cda9a742432ac6ca8c05ebd19c7f09d09cb1/lib/internal/webstreams/adapters.js#L428-L433). Unfortunately this means we need to wrap it, but there is a better way to do this that I'm working on now (overriding the `pull()` method instead of all the logic being handled in `start()`)

2024-03-21 00:50 UTC, flakey5 commented on plugins/api.ts
> +          }
How about sending an `error` event w/ the error details then closing the stream? E.g.
```
event: error
data: ...stringified fastify error...
```

2024-03-21 02:36 UTC, flakey5 commented on ai-providers/mistral.ts
> +class MistralByteSource implements UnderlyingByteSource {
Unfortunately I don't think so, Mistral's stream function returns an `AsyncGenerator` and this is the best way I can think of to go from that to a `ReadableStream`. The next best thing I can think of would be using `TransformStream` in the `askStream` function but it wouldn't be respecting back pressure:
```js
const { readable, writable } = new TransformStream()
const writer = writable.getWriter()
async function work() {
  while(true) {
    const { done, value } = await response.next()
    if (done !== undefined && done) {
      await writer.close()
      break
    }

    // error handling...

    const { content } = value.choices[0].delta
    await writer.write(/* encoded content... */)
  }
}
work()
return readable
```

2024-03-21 08:41 UTC, mcollina requested changes

2024-03-21 08:41 UTC, mcollina commented on ai-providers/mistral.ts
> +class MistralByteSource implements UnderlyingByteSource {
You don't need to got to a WHATWG `ReadableStream`? Just use `stream.Readable.from(...)` and you'd be good to go.

2024-03-21 17:14 UTC, flakey5 commented on ai-providers/mistral.ts
> +class MistralByteSource implements UnderlyingByteSource {
If we care about the response being in the server sent event format, then we'll still need to do something similar to the `TransformStream` example above. The `AsyncGenerator` only contains the chat completion chunk data, it isn't from the stream obtained from the http request to Mistral's api. The Mistral client also parses the json response for us as well, so the `AsyncGenerator`'s data is a bunch of `object`s. if we just directly passed the contents of it along to the client, the body would look something like
```
[object Object][object Object][object Object]
```
instead of the server sent event format
```
event: content
data: {"response": "..."}
```

It's a similar thing with the OpenAI client, except that it gives us a byte stream which means we need to parse the chat completion chunk ourselves: https://github.com/platformatic/ai-warp/blob/f41093ad24c682a195b1197597725da97583326d/ai-providers/open-ai.ts#L50-L51

If we did pass in just the raw stream from the OpenAI client, it'd look something like this:
```
{"choices": [{"content": "..."}, ...], ...}{"choices": [{"content": "..."}, ...], ...}{"choices": [{"content": "..."}, ...], ...}
```

2024-03-26 19:36 UTC, merged