Add Authorization header to OpenAPI docs
platformatic/ai-warp-old pull request #61
Opened 2024-05-14 18:26 UTC by flakey5

Closes #43

2024-05-15 11:03 UTC, ivan-tymoshenko requested changes
Hi, thank you for the PR. Adding a security schema seems like a correct idea from the spec point of view, but unfortunatelly this would not work with other platformatic openapi tools like client or composer. I think you need to add the authorization header to each route schema.

You will probably need the `onRoute` hook for that.
https://fastify.dev/docs/latest/Reference/Hooks/#onroute

And add the test for that, please.

2024-05-15 11:03 UTC, ivan-tymoshenko commented on index.ts
> +      ...opts
Why do you need to copy the the opts here?

2024-05-20 12:19 UTC, ivan-tymoshenko requested changes

2024-05-20 12:19 UTC, ivan-tymoshenko commented on plugins/api.ts
> +      security,
Again, this is not enough for platformatic openapi tools. They just don't check for the security schemas now. What you need to do it to add an "Authorization" header to the route headers schema.

And  I think it's better to use the `onRoute` hook to intercept app routes that you want to update.

2025-07-21 09:03 UTC, simone-sanfratello commented
We archived the current repository in favor of https://github.com/platformatic/ai-warp

2025-07-21 09:03 UTC, closed without merging